config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'home#index'
  get 'complete/:id', to: 'home#complete', as: 'complete_task_instance'

  get 'current_user/edit', as: 'edit_current_user'
  patch 'current_user/update', as: 'update_current_user'
  delete 'current_user/delete', as: 'delete_current_user'
  delete 'current_user/destroy', as: 'destroy_current_user'
  resources :features
  resources :permissions
  resources :rewards
  resources :roles
  resources :tasks
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # mount Sidekiq::Web => '/sidekiq'
end

app/models/reward.rb
class Reward < ApplicationRecord
  include SoftDeletable

  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_one :schedule

  after_save :set_user_reward

  def avatar
    abbreviation
  end

  def abbreviation
    name[0..1]
  end

  def set_user_reward
    return unless user.rewards.count == 1

    user.update(next_reward_id: id)
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  def index
    @rewards = Reward.where(user_id: current_user.id).order(:name)
  end

  def show; end

  def new
    @reward = Reward.new
  end

  def edit; end

  def create
    @reward = Reward.new(reward_params.merge(user_id: current_user.id))

    if @reward.save
      redirect_to rewards_path, notice: 'Reward was successfully created.'
    else
      render :new
    end
  end

  def update
    if @reward.update(reward_params)
      redirect_to rewards_path, notice: 'Reward was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @reward.soft_delete
    redirect_to rewards_path, notice: 'Reward was successfully destroyed.'
  end

  private

  def set_reward
    @reward = Reward.find(params[:id])
    redirect_to rewards_path unless @reward.user_id == current_user.id
  end

  def reward_params
    params.expect(reward: [:name])
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward, local: true) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Rewards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= link_to reward.name, edit_reward_path(reward) %></td>
        <td>
          <%= link_to 'X', reward_path(reward), method: :delete, id: "delete_#{reward.id}", data: { confirm: 'Are you sure?' } %>
          &nbsp;
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reward.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @reward.user_id %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @reward.abbreviation %>
</p>

<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>