config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'home#index'
  get 'complete/:id', to: 'home#complete', as: 'complete_task_instance'

  get 'current_user/edit', as: 'edit_current_user'
  patch 'current_user/update', as: 'update_current_user'
  delete 'current_user/delete', as: 'delete_current_user'
  delete 'current_user/destroy', as: 'destroy_current_user'
  resources :features
  resources :permissions
  resources :rewards
  resources :roles
  resources :tasks
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # mount Sidekiq::Web => '/sidekiq'
end

app/controllers/current_user_controller.rb
class CurrentUserController < ApplicationController
  before_action :set_current_user
  before_action :check_destroy_confirm, only: [:destroy]

  def edit; end

  def update
    respond_to do |format|
      if @current_user.update(current_user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def delete; end

  def destroy
    @current_user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
    end
  end

  private

  def set_current_user
    @current_user = current_user
  end

  def current_user_params
    params.permit(:confirm, :email, :name, :password, :password_confirmation, :time_zone)
  end

  def check_destroy_confirm
    return if current_user_params[:confirm] == @current_user.name

    redirect_to edit_current_user_path, notice: 'You must type your user name exactly to confirm deletion.'
  end
end

app/helpers/current_user_helper.rb
module CurrentUserHelper
end

app/views/current_user/delete.html.erb
<h1>Delete <%= @current_user.name %> and all associated data</h1>

<p>
  We are sorry to see you go, but are happy to make it an easy process. Please type "<%= @current_user.name %>"
  in the field below to delete your user:
</p>
<%= form_tag destroy_current_user_path, method: :delete do |form| %>
  <div class="field">
    <%= label_tag :confirm %>
    <%= text_field_tag :confirm %>
  </div>
  <div class="actions">
    <%= submit_tag "Delete My Account & All of My Data" %>
  </div>
<% end %>

app/views/current_user/edit.html.erb
<h1>Editing <%= @current_user.name %></h1>
<%= form_tag update_current_user_path, method: :patch do %>
  <% if @current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @current_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, @current_user.email, autofocus: true %>
  </div>

  <div class="field">
    <%= label_tag :name %>
    <%= text_field_tag :name, @current_user.name %>
  </div>

  <div class="field">
    <%= label_tag :time_zone %>
    <select name="time_zone" id="time_zone">
      <% ActiveSupport::TimeZone.all.each do |zone| %>
        <option value="<%= zone.name %>"<%= 'selected="selected"' if zone.name == @current_user.time_zone %>>
          <%= zone.to_s %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>

  <div class="field">
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation %>
  </div>

  <div class="actions">
    <%= submit_tag %>
    <%= link_to 'Delete User', delete_current_user_path, method: :delete %>
  </div>
<% end %>