config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'home#index'
  get 'complete/:id', to: 'home#complete', as: 'complete_task_instance'

  get 'current_user/edit', as: 'edit_current_user'
  patch 'current_user/update', as: 'update_current_user'
  delete 'current_user/delete', as: 'delete_current_user'
  delete 'current_user/destroy', as: 'destroy_current_user'
  resources :features
  resources :permissions
  resources :rewards
  resources :roles
  resources :tasks
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # mount Sidekiq::Web => '/sidekiq'
end

app/models/action.rb
class Action < ApplicationRecord
  has_and_belongs_to_many :permissions

  validates :name, presence: true, uniqueness: true

  CREATE  = 'create'.freeze
  DELETE  = 'delete'.freeze
  DESTROY = 'destroy'.freeze
  EDIT    = 'edit'.freeze
  INDEX   = 'index'.freeze
  NEW     = 'new'.freeze
  SHOW    = 'show'.freeze
  UPDATE  = 'update'.freeze

  NAMES = [CREATE, DELETE, DESTROY, EDIT, INDEX, NEW, SHOW, UPDATE].freeze
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :permissions

  validates :name, presence: true, uniqueness: true
end

app/models/happiness.rb
class Happiness < ApplicationRecord
  self.table_name = "happiness"
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :actions
  belongs_to :feature

  validates :feature, presence: true

  def create?
    actions.where(name: Action::CREATE).any?
  end

  def destroy?
    actions.where(name: Action::DESTROY).any?
  end

  def edit?
    actions.where(name: Action::EDIT).any?
  end

  def index?
    actions.where(name: Action::INDEX).any?
  end

  def new?
    actions.where(name: Action::NEW).any?
  end

  def show?
    actions.where(name: Action::SHOW).any?
  end

  def update?
    actions.where(name: Action::UPDATE).any?
  end

  def to_s
    "#{feature.name}: " \
    "#{'C' if create?} " \
    "#{'D' if destroy?} " \
    "#{'E' if edit?} " \
    "#{'I' if index?} " \
    "#{'N' if new?} " \
    "#{'S' if show?} " +
      ('U' if update?).to_s
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
end

app/models/reward.rb
class Reward < ApplicationRecord
  include SoftDeletable

  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_one :schedule

  after_save :set_user_reward

  def avatar
    abbreviation
  end

  def abbreviation
    name[0..1]
  end

  def set_user_reward
    return unless user.rewards.count == 1

    user.update(next_reward_id: id)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :permissions
  has_many :user

  validates :name, presence: true, uniqueness: true

  def feature?(name)
    feature = Feature.find_by(name: name.downcase)
    permissions.any? { |p| p.feature_id == feature.id } unless feature.nil?
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validate :occurrences_or_due_date?

  belongs_to :model, polymorphic: true

  private

  def occurrences_or_due_date?
    return if occurrences.present? || due_date.present?

    errors.add(:occurences_or_due_date, 'Either occurences or due date is required')
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include SoftDeletable

  # @TODO: extract this and other constants to a settings object?
  XP_FACTOR = 10

  belongs_to :user
  has_many :task_instances, dependent: :destroy

  validates :name, presence: true
  validates :frequency, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 31 }
  validates :size, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
  validates :user_id, presence: true

  before_save :set_xp

  def set_xp
    self.xp = frequency * size * XP_FACTOR
  end

  def bonus_xp
    (xp * (user.xp_multiplier - 1)).to_i
  end

  private

  def xp=(value)
    super
  end
end

app/models/task_instance.rb
class TaskInstance < ApplicationRecord
  belongs_to :task

  validates :task_id, presence: true

  def toggle_complete!
    if completed?
      uncomplete!
    else
      complete!
    end
  end

  def complete!
    update(completed_at: DateTime.new)
    task.user.add_xp(task.xp)
    task.user.increment_xp_multiplier!
  end

  def uncomplete!
    update(completed_at: nil)
    task.user.remove_xp(task.xp)
    task.user.decrement_xp_multiplier!
  end

  def completed?
    !completed_at.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  include DateInZone

  has_secure_password

  belongs_to :role
  belongs_to :next_reward, class_name: 'Reward', optional: true
  has_and_belongs_to_many :earned_rewards,
                          -> { unscope(where: :deleted_at) },
                          class_name: 'Reward',
                          join_table: 'rewards_users',
                          association_foreign_key: 'reward_id'
  has_many :rewards
  has_many :tasks, dependent: :destroy
  has_many :task_instances, through: :tasks

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :time_zone, presence: true, time_zone: true
  validates :xp_multiplier, not_less_than_one: true

  TASKS_PER_DAY     = 5
  XP_PER_LEVEL      = 1000
  XP_MULT_INCREMENT = 0.1
  MAX_XP_MULT       = 2

  def avatar
    name[0..1].downcase.capitalize
  end

  def add_xp(amount)
    self.xp += (amount * xp_multiplier)
    level_up
    save
  end

  def remove_xp(amount)
    return if (amount * xp_multiplier) > xp_this_level

    add_xp(amount * -1)
  end

  def increment_xp_multiplier!
    return if xp_multiplier >= MAX_XP_MULT

    self.xp_multiplier += XP_MULT_INCREMENT
    save
  end

  def decrement_xp_multiplier!
    return if xp_multiplier == 1

    self.xp_multiplier -= XP_MULT_INCREMENT
    save
  end

  def reset_xp_multiplier!
    self.xp_multiplier = 1
    save
  end

  def xp_this_level
    xp % XP_PER_LEVEL
  end

  def progress_to_level
    xp_this_level.to_f / XP_PER_LEVEL
  end

  def task_list(date = today_in_zone(time_zone))
    raise ArgumentError, 'Date cannot be in the future' if date > today_in_zone(time_zone)

    task_instances.where(created_on: date).to_a
  end

  def build_task_list
    return if task_list?

    reset_xp_multiplier! unless tasks_completed?(yesterday_in_zone(time_zone))
    # TODO: Use algorithm to select, not random
    tasks.order(Arel.sql('RANDOM()')).first(TASKS_PER_DAY).each do |task|
      TaskInstance.create(task: task, created_on: today_in_zone(time_zone))
    end
  end

  def task_list?(date = today_in_zone(time_zone))
    tasks.empty? || task_list(date).any?
  end

  private

  def level_up
    return unless level_up?

    self.level = new_level
    earn_reward
    set_next_reward
  end

  def level_up?
    level < new_level
  end

  def new_level
    (xp / XP_PER_LEVEL).floor + 1
  end

  def earn_reward
    earned_rewards << next_reward if next_reward
  end

  def set_next_reward
    # TODO: Use algorithm to select, not random
    self.next_reward = rewards.order(Arel.sql('RANDOM()')).first
  end

  def tasks_completed?(date = today_in_zone(time_zone))
    task_list(date).none? do |instance|
      instance.completed_at.nil?
    end
  end

  def xp=(value)
    super
  end

  def xp_multiplier=(value)
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_time(time)
    time.strftime('%I:%M %p')
  end

  def humanize_date(date)
    date.strftime('%A, %B %d, %Y')
  end

  def humanize_datetime(date_time)
    date_time.strftime('%A, %B %d, %Y - %I:%M %p')
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_conditional_link.html.erb
<%= link_to(name.capitalize, controller: name) if @current_user.role.feature?(name) %>

app/views/layouts/_guest_links.html.erb
<%= link_to 'Log In', login_path %>

app/views/layouts/_links.html.erb
<div class="links">
  <div class="hamburger">
    <span>_</span>
    <span>_</span>
    <span>_</span>
  </div>
  <div class="links-list">
    <% if current_user %>
      <%= render partial: 'layouts/user_links' %>
    <% else %>
      <%= render partial: 'layouts/guest_links' %>
    <% end %>
  </div>
</div>

app/views/layouts/_permission_checks_table.html.erb
<table>
  <thead>
  <tr>
    <th>Feature</th>
    <th>Create</th>
    <th>Destroy</th>
    <th>Edit</th>
    <th>Index</th>
    <th>New</th>
    <th>Show</th>
    <th>Update</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% permissions.each do |permission| %>
    <tr>
      <td><%= link_to permission.feature.name, edit_permission_path(permission) %></td>
      <td><%= '&#10003;'.html_safe if permission.create? %></td>
      <td><%= '&#10003;'.html_safe if permission.destroy? %></td>
      <td><%= '&#10003;'.html_safe if permission.edit? %></td>
      <td><%= '&#10003;'.html_safe if permission.index? %></td>
      <td><%= '&#10003;'.html_safe if permission.new? %></td>
      <td><%= '&#10003;'.html_safe if permission.show? %></td>
      <td><%= '&#10003;'.html_safe if permission.update? %></td>
      <td>
        <%= link_to 'X', permission_path(permission), method: :delete, id: "delete_#{permission.id}", data: { confirm: 'Are you sure?' } %>
        &nbsp;
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_user_links.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'My Account', edit_current_user_path %>
<%= render partial: 'layouts/conditional_link', locals: { name: 'rewards' } %>
<%= render partial: 'layouts/conditional_link', locals: { name: 'tasks' } %>
<%= render partial: 'layouts/conditional_link', locals: { name: 'features' } %>
<%= render partial: 'layouts/conditional_link', locals: { name: 'permissions' } %>
<%= render partial: 'layouts/conditional_link', locals: { name: 'roles' } %>
<%= render partial: 'layouts/conditional_link', locals: { name: 'users' } %>
<%= link_to 'Log Out', logout_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chores</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name%>">

    <%= render partial: 'layouts/links' %>
    <p class=”notice”><%= notice %></p>

    <div class="content">
      <%= yield %>
    </div>

  </body>
</html>